<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/Proto/User.proto

/**
 * Protobuf type <code>UserRoles</code>
 */
class UserRoles
{
    /**
     * Generated from protobuf enum <code>USER_ROLES_ROLE_ADMIN = 0;</code>
     */
    const USER_ROLES_ROLE_ADMIN = 0;
    /**
     * Generated from protobuf enum <code>USER_ROLES_ROLE_USER = 1;</code>
     */
    const USER_ROLES_ROLE_USER = 1;
    /**
     * Generated from protobuf enum <code>USER_ROLES_ROLE_MANAGER = 2;</code>
     */
    const USER_ROLES_ROLE_MANAGER = 2;

    private static $valueToName = [
        self::USER_ROLES_ROLE_ADMIN => 'USER_ROLES_ROLE_ADMIN',
        self::USER_ROLES_ROLE_USER => 'USER_ROLES_ROLE_USER',
        self::USER_ROLES_ROLE_MANAGER => 'USER_ROLES_ROLE_MANAGER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

