<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/Proto/User.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\RepeatedField;

/**
 * Generated from protobuf message <code>User</code>.
 */
class User extends Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>.
     */
    protected $id;
    /**
     * Generated from protobuf field <code>optional string uuid = 2;</code>.
     */
    protected $uuid;
    /**
     * Generated from protobuf field <code>repeated .UserRoles roles = 3;</code>.
     */
    private $roles;
    /**
     * Generated from protobuf field <code>string password = 4;</code>.
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string firstName = 5;</code>.
     */
    protected $firstName = '';
    /**
     * Generated from protobuf field <code>string secondName = 6;</code>.
     */
    protected $secondName = '';
    /**
     * Generated from protobuf field <code>string birthday = 7;</code>.
     */
    protected $birthday = '';
    /**
     * Generated from protobuf field <code>optional string avatarPath = 8;</code>.
     */
    protected $avatarPath;
    /**
     * Generated from protobuf field <code>string email = 9;</code>.
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string address = 10;</code>.
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string phoneNumber = 11;</code>.
     */
    protected $phoneNumber = '';
    /**
     * Generated from protobuf field <code>.Gender gender = 12;</code>.
     */
    protected $gender = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int                                                $id
     * @var string                                             $uuid
     * @var array<int>|\Google\Protobuf\Internal\RepeatedField $roles
     * @var string                                             $password
     * @var string                                             $firstName
     * @var string                                             $secondName
     * @var string                                             $birthday
     * @var string                                             $avatarPath
     * @var string                                             $email
     * @var string                                             $address
     * @var string                                             $phoneNumber
     * @var int                                                $gender
     *                                                         }
     */
    public function __construct($data = null)
    {
        GPBMetadata\Src\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>.
     *
     * @return int
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : 0;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional int32 id = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string uuid = 2;</code>.
     *
     * @return string
     */
    public function getUuid()
    {
        return isset($this->uuid) ? $this->uuid : '';
    }

    public function hasUuid()
    {
        return isset($this->uuid);
    }

    public function clearUuid()
    {
        unset($this->uuid);
    }

    /**
     * Generated from protobuf field <code>optional string uuid = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, true);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .UserRoles roles = 3;</code>.
     *
     * @return RepeatedField
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * Generated from protobuf field <code>repeated .UserRoles roles = 3;</code>.
     *
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     *
     * @return $this
     */
    public function setRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::ENUM, UserRoles::class);
        $this->roles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 4;</code>.
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 4;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, true);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string firstName = 5;</code>.
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Generated from protobuf field <code>string firstName = 5;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, true);
        $this->firstName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secondName = 6;</code>.
     *
     * @return string
     */
    public function getSecondName()
    {
        return $this->secondName;
    }

    /**
     * Generated from protobuf field <code>string secondName = 6;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSecondName($var)
    {
        GPBUtil::checkString($var, true);
        $this->secondName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string birthday = 7;</code>.
     *
     * @return string
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Generated from protobuf field <code>string birthday = 7;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setBirthday($var)
    {
        GPBUtil::checkString($var, true);
        $this->birthday = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string avatarPath = 8;</code>.
     *
     * @return string
     */
    public function getAvatarPath()
    {
        return isset($this->avatarPath) ? $this->avatarPath : '';
    }

    public function hasAvatarPath()
    {
        return isset($this->avatarPath);
    }

    public function clearAvatarPath()
    {
        unset($this->avatarPath);
    }

    /**
     * Generated from protobuf field <code>optional string avatarPath = 8;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setAvatarPath($var)
    {
        GPBUtil::checkString($var, true);
        $this->avatarPath = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 9;</code>.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 9;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 10;</code>.
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 10;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, true);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 11;</code>.
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Generated from protobuf field <code>string phoneNumber = 11;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, true);
        $this->phoneNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Gender gender = 12;</code>.
     *
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>.Gender gender = 12;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, Gender::class);
        $this->gender = $var;

        return $this;
    }
}
